### ISSUE TITLE
I cant select or generate code pattern

### ISSUE THREAD

**Issue by insomnia77** [sbtqa/Jedi#6]
I have completed two steps, but I cant select or generate code pattern  (screenshots attached). 
![jedi-master1](https://cloud.githubusercontent.com/assets/11542492/26523738/fe2e5806-4325-11e7-9851-31f28f9bd20b.jpg)
![jedi-master2](https://cloud.githubusercontent.com/assets/11542492/26523739/018385a8-4326-11e7-8b27-14fb91ceaae7.png)

There is always empty Type here and Generate button does not works.
![jedi-master3](https://cloud.githubusercontent.com/assets/11542492/26523740/07b830fe-4326-11e7-8454-f1418e1fea9b.jpg)

**Comment by cyberspaceru** [comment]
Of course, I'm sorry. I forgot describe one action, you have to click on the 'Update' button in the left corner of the menu before You click on the 'Generate' button.

![07b830fe-4326-11e7-8454-f1418e1fea9b](https://cloud.githubusercontent.com/assets/3779588/26526257/cb5dfc6e-439e-11e7-84c9-29aa98fc2f01.jpg)

Thank You!

**Comment by artsok** [comment]
@insomnia77 , Did problem solve?

**Comment by insomnia77** [comment]
@artsok @cyberspaceru  Yes. Thanks. Now I am creating my own pattern :)
